name: Build Docker Container and Push to Registry
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gzt5142/htdemo

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: "Build, Push image"
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: iameskild
          DOCKER_PASSWORD: ${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

